version: '3.6'

services:

  tasks_notifier:
    build: .
    volumes:
      - .:/app
    restart: always
    environment:
      - DEBUG:${DEBUG}
      - DATABASE_URL=postgresql://${BOT_DB_USER}:${BOT_DB_PASSWORD}@${BOT_DB_HOST}:${BOT_DB_PORT}/${BOT_DB_NAME}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "80:80"

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    ports:
      - "6380:6379"